### ISSUE TITLE
Consider cross-backend vaccination querying

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor#422]
We [currently query TPP](https://github.com/opensafely/cohort-extractor/pull/103) in a way that's quite specific to their vaccinations implementation. Example:

```python
recent_flu_vaccine = patients.with_tpp_vaccination_record(
    target_disease_matches="INFLUENZA",
    on_or_after="2018-01-01",
    find_last_match_in_period=True,
    returning="date",
)
```

We also want to query EMIS, where Covid vax appear in the standed coded events table.

Ideally we'd use a single method for both.

There's an argument for a covid19-specific function here because of its specific utility.

There's also some dedupe logic that needs to be applied at some point. @chris-tpp suggests treating as dupes any two vax within 2 weeks of each other which share the same dose number (i.e. dose 1 or dose 2). 

We could also consider excluding manual filings which at least in TPP sometimes turn up as recorded by VMP (when the automatic filing is always by AMP/AMPP).

This also ties into conversations we've had about a "variables library". Could "has_covid19_vaccine" be composed of lower-level bits and then exposed as a "library variable"?

**Comment by HelenCEBM** [comment]
Just to note the method shown above is not what we use for most vaccines in TPP, because to be sure to count all vaccines received by patients we _also_ query the coded events table and medications issued, as some are sometimes issued in non-standard ways.  

We then combine then into a single field, e.g.:
```
flu_vaccine=patients.satisfying(
        """
        flu_vaccine_tpp_table OR
        flu_vaccine_med OR
        flu_vaccine_clinical
        """,
    ),
```
We have only checked the vaccines table for COVID because we are assured these are all captured in the vaccines table (at least for now but this could change as they become more established).

**Comment by HelenCEBM** [comment]
This is now done @inglesp ?

**Comment by inglesp** [comment]
Yes!
