### ISSUE TITLE
Drop pyodbc dependency

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#460]
See note at https://github.com/opensafely-core/cohort-extractor/blob/master/requirements.in#L14-L19.  There are no longer hyphens in EMIS fieldnames.

**Comment by evansd** [comment]
Actually, I think we might end up doing the reverse here which is to drop cTDS and either switch back to using pyodbc or use something like pymssql.

The reason for exploring different db libraries was that we were having problems downloading large result sets with pyodbc. I thought we had solved this with cTDS but it turned out we hadn't so in #322 we switched to using batched (retry-able) downloads. This means we can be less picky about which db library we use and should go for whichever seems to most mainstream and well-supported.

**Comment by evansd** [comment]
Closed in favour of #704
