### ISSUE TITLE
Support low number suppression in measures generation

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor#504]
[When we generate measures](https://github.com/opensafely-core/cohort-extractor/blob/27a542b781a38ebebb77b0e36ebc13e9eb46364b/cohortextractor/cohortextractor.py#L307-L320), we should automatically suppress low numbers per our policy (<=5)

This is on the happy path to being able to publish measures without requiring a manual disclosure review.

Don't forget to update [the docs](https://docs.opensafely.org/en/latest/measures/)

**Comment by benbc** [comment]
Should be configurable -- default to 5.

**Comment by benbc** [comment]
@sebbacon My understanding of what's required here:

* For every measure, if the numerator is less than or equal to the threshold, replace it with zero (and hence the value of the measure will also be zero).
* Threshold can be specified per measure, defaults to 5.

Is that what you're expecting?

**Comment by sebbacon** [comment]
Sounds right,  @helencebm can you confirm as a Real Life user?

**Comment by HelenCEBM** [comment]
Sounds good. I think we would also need to replace any denominators less than the threshold (though this will be much less common!)

If possible, it would probably be useful to have a report output to show which fields have been subject to suppression, for sense checking (not for release), e.g. if all zeros have come out is that because all the values were suppressed or that there were no non-zero values in the first place?

Something like:
```
File X1 (oranges_by_apples_2020-01-01): numerators: n values suppressed, denominators: 0 values suppressed
File X2 (oranges_by_apples_2020-02-01): ...
...
```

**Comment by HelenCEBM** [comment]
@LFISHER7 may have some thoughts having used measures a lot recently

**Comment by benbc** [comment]
@sebbacon @HelenCEBM @LFISHER7 @alexwalkercebm @wjchulme 

After talking to Helen, Louis and Alex, here's what I've come up with as a spec for this work.

Please let me know if you don't think this is what's needed.

## Acceptance criteria

Suppress numbers in numerator or denominator that are greater than zero and lower than or equal to a threshold.

Suppression is optional. Threshold is always 5.

Replace suppressed numbers with `NaN`. Resulting value should then also be `NaN`.

When the sum of suppressed values is less than the threshold, suppress the smallest of the values that exceeds the threshold.

Suppression is clearly logged so that suprising behaviour can be debugged.

## Out of scope

Report on fields that have been subject to suppression. This is clearly useful during study development, but is out of scope for this work. We don't currently have such a reporting mechanism and the use of `NaN` for suppressed values gives a strong hint that may be good enough until the reporting mechanism exists.

Disallow studies that include small numbers in the results. The ultimate goal here is to get closer to review-less publication; one prerequisite there is making sure that studies don't include small numbers in the results. However suppression is not the only way to remove small numbers: for some studies it might be more appropriate to filter out the records altogether or to roll up the records with small numbers into aggregates. So it seems that the right approach here is to decouple mechanism and policy, provide tools to make it easy to avoid small numbers (of which suppression is one) and then enforce avoidance separately.

Provide an option to round _all_ numbers in numerators and denominators to the nearest 5. This is another way to avoid the disclosivity of small numbers that may be better in some cases and can also be implemented automatically.

**Comment by wjchulme** [comment]
> When the sum of suppressed values is less than the threshold, suppress the smallest of the values that exceeds the threshold.

There's a decision to be made about what to do when there's more than one cell whose value is equal to the minimum value. When I implemented this I just suppressed the first one it found. But in theory, you could reorder your categories and get the routine to suppress a different cell (and reveal the previously suppressed cell). So maybe suppress _all_ cells whose value is the minimum?

PS I hate that we have to even think about this because it's basically trivial nonsense that exposes the flaws in crude small number suppression as a means to preserve privacy

**Comment by benbc** [comment]
@wjchulme Ugh! I think you're right. Thanks.

Having spent a few days listening to people talk about this and thinking it through myself, my instinct is that there's probably _always_ a better solution than this crude censoring approach: rounding, re-classifying or filtering. But since I've only been on the team for a week, I don't think my opinion should hold any weight.

**Comment by HelenCEBM** [comment]
> So maybe suppress all cells whose value is the minimum?

I would think this is fine - it will be rare, and probably will prompt the researcher to recategorise or find another solution instead.

I'm wondering what "Suppression is clearly logged" will comprise, given that "Report on fields that have been subject to suppression" is listed as out of scope?

**Comment by benbc** [comment]
@HelenCEBM we'll include information in the action's logs which, I believe, should be visible to you somehow. I still need to confirm exactly how this works.

**Comment by sebbacon** [comment]
>> I hate that we have to even think about this because it's basically trivial nonsense that exposes the flaws in crude small number suppression as a means to preserve privacy
>
> my instinct is that there's probably always a better solution than this crude censoring approach: rounding, re-classifying or filtering

I couldn't agree more and I think most other statisticians on our team would also agree.

However, the unfortunate reality is that this is (a) the way the system currently insists it should work (including ONS) and (b) our DSA compels us to use this approach. As always we should aim to do better, but as a minimal (semi-) automated step this is necessary, unpleasant though it is. 

> I'm wondering what "Suppression is clearly logged" will comprise, given that "Report on fields that have been subject to suppression" is listed as out of scope?

@HelenCEBM, I think @benbc means "report in public *without having to log into L4*" - e.g. for public auditing etc

**Comment by benbc** [comment]
@HelenCEBM Sorry to have been so slow replying. The logging will be in the log files in the metadata directory on the server. There are new log lines that look like this:

```
2021-04-27 11:57:57 [info     ] Suppressed small numbers in column has_chronic_liver_disease in measure liver_disease_by_stp [cohortextactor.reporter] 
2021-04-27 11:57:57 [info     ] Suppressed small numbers in column population in measure liver_disease_by_stp [cohortextactor.reporter] 
```

I know that's not ideal since it's a bit of a pain to look at those files, but I hope that in combination with fact that the suppressed values show up as blank (rather than zero) it will be easy enough for you to figure out what's going on.
