### ISSUE TITLE
 multiple positive SGSS results using `restrict_to_earliest_specimen_date=True`

### ISSUE THREAD

**Issue by andrewscolm** [opensafely-core/cohort-extractor#745]
Using `patients.with_test_result_in_sgss(
                pathogen="SARS-CoV-2",
                test_result="positive",
                restrict_to_earliest_specimen_date=True,....)` there are 78 patients with a second positive SGSS at least 21 days after the first positive SGSS between 2020-02-01 and 2021-11-28. Using `restrict_to_earliest_specimen_date=True` should prevent multiple positive SGSS results per patient.

**Comment by evansd** [comment]
All `restrict_to_earliest_specimen_date` really does is to switch to using the Earliest Specimen Date dataset as supplied by PHE. So if there are unexpected multiple results in there that's a feature of the underlying dataset. My feeling is that this is an issue that should be surfaced in the documentation, rather than something we should attempt to work around in the cohortextractor. But maybe there are other arguments in favour of that?

**Comment by andrewscolm** [comment]
Thanks Dave, I agree it sounds like this should have been in the documentation and not cohortextractor.
