### ISSUE TITLE
Document vaccine names notebook

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#830]
Vaccine names change. However, researchers only discover this when their studies return unexpected results (see [this Slack thread][1], for example). @HelenCEBM has several notebooks that report the most recent vaccine names. We should learn how to run the notebooks, and how to report the most recent vaccine names.

The notebooks are within `/e/helen/raw-data-plausibility-checks` (L3), which is a clone of [opensafely/raw-data-plausibility-checks][]. The HTML versions of the notebooks are within:

- `/srv/medium_privacy/workspaces/raw-data-plausibility-checking` (L3 VM)
- `/d/Level4Files/workspaces/raw-data-plausibility-checking` (L4)

There is a separate issue for replacing vaccine names with snomed codes.

[1]: https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1654676131986419
[opensafely/raw-data-plausibility-checks]: https://github.com/opensafely/raw-data-plausibility-checks/tree/bp-cod-primary-care-domain-refset

**Comment by HelenCEBM** [comment]
There is just one notebook for this particular task but it was developed in the server 
- [ ] I need to release the code as a txt file in order to recreate it outside of the server. 

The notebook is run in line with [these](https://bennettinstitute-team-manual.pages.dev/tech-group/playbooks/opensafely-tpp-notebooks/) instructions once [this](https://github.com/ebmdatalab/team-manual/pull/192) PR is completed. 

However, it currently still requires someone to discover that the name has changed before we run it. There are several possible solutions e.g.:
- make this automatable / a reusable action etc for easier running
- create a script that runs routinely to detect any changes in vaccine names and alert us before it breaks someone's study
- make the whole vaccine reference table available in L4 so users can more easily self-serve vaccine names for any target disease (not just COVID vaccines)
- Use the four-digit TPP vaccine codes instead of names (but we would need to make the ref table easily accessible to make these meaningful) 
- Use SNOMED codes

**Comment by milanwiedemann** [comment]
made some changes to document how to use these notebooks to the team manual https://github.com/ebmdatalab/team-manual/pull/250

**Comment by milanwiedemann** [comment]
updates merged and available here https://bennettinstitute-team-manual.pages.dev/tech-group/playbooks/opensafely-tpp-notebooks/

**Comment by iaindillingham** [comment]
I think [opensafely#vaccination-names](https://github.com/opensafely/vaccination-names) addresses this issue.
