### ISSUE TITLE
Ethnicity in SUS documentation

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/cohort-extractor#850]
https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_ethnicity_from_sus

> As a user I want to know which heading is which from the documentation and how the groupings are done so I can sense check and quality assure results.

Currently there is minimal information in the documentation here about what `group_6` and `group_16` might be. It makes it hard for a user to check particularly as we have multiple codelists for ethnicity now.

**Comment by alexwalkerepi** [comment]
The implementation is hardcoded into `cohortextractor`

[here](https://github.com/opensafely-core/cohort-extractor/blob/9075019c39925078c388c2a61997199cd7c0475d/cohortextractor/tpp_backend.py#L2055-L2072) for 6 category, 

[here](https://github.com/opensafely-core/cohort-extractor/blob/9075019c39925078c388c2a61997199cd7c0475d/cohortextractor/tpp_backend.py#L2086-L2102) for 16 category

The A to S categories in the code should correspond to the category labels for the 2001 census categories [here](https://www.datadictionary.nhs.uk/data_elements/ethnic_category.html?hl=ethnicity).

I'll add this categorisation to the docs.

**Comment by alexwalkerepi** [comment]
Somewhat separately, it is slightly odd that we hardcode the conversion of letters to numbers. The numbers are mostly a historical OpenSAFELY coding pattern so far as I remember. While the categories above fit with 2001 census categories used in codelists such as [this one](https://www.opencodelists.org/codelist/opensafely/ethnicity-snomed-0removed/2e641f61/), they do not fit with others, including notably the [original CTV3 ethnicity codelist](https://www.opencodelists.org/codelist/opensafely/ethnicity/2020-04-27/).

Ideally there'd at least be an option to return the raw letter values so that custom mappings can be used.

**Comment by alexwalkerepi** [comment]
> Ideally there'd at least be an option to return the raw letter values so that custom mappings can be used.

Turns out that there _is_ this option already (`returning="code"`) and I just didn't notice [in the docs](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_ethnicity_from_sus).
